"""empty message

Revision ID: 41f3931f2935
Revises: 2ba8bd54e39b
Create Date: 2024-12-18 19:55:15.370069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41f3931f2935'
down_revision = '2ba8bd54e39b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('user_creation_date_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint('user_creation_date_key', ['creation_date'])

    # ### end Alembic commands ###
